### ISSUE TITLE
The pt_BR language is not working

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/ch.openboard.OpenBoard#1]
![captura de tela de 2018-12-18 17-28-46](https://user-images.githubusercontent.com/26097419/50177955-0b7b3880-02e2-11e9-83e9-7f37ff914f02.png)

**Comment by JBBgameich** [comment]
Are you sure this language is supported upstream? I can't find a translations file for it [here](https://github.com/OpenBoard-org/OpenBoard/tree/master/resources/i18n).

**Comment by LeandroStanger** [comment]
https://github.com/OpenBoard-org/OpenBoard/blob/master/resources/i18n/OpenBoard_pt_BR.ts

**Comment by JBBgameich** [comment]
Oh right. No idea why I didn't see it ...
I guess it's not only this language but translations might be broken in general. I'll look into fixing them tomorrow.

**Comment by JBBgameich** [comment]
https://github.com/OpenBoard-org/OpenBoard/blob/6b11902b52f1dd0f36bb0d9c758e9dcad9bcfe9e/src/frameworks/UBPlatformUtils_linux.cpp#L77

The cause for the issue seems to be another incorrect path which isn't using QtStandardPaths. Shouldn't take a lot of time to fix.

**Comment by JBBgameich** [comment]
Actually it seems like the i18n files are not even installed by qmake...

**Comment by JBBgameich** [comment]
Verified at least the German translation is working. I assume the other languages are working as well, if not, feel free to re-open this issue.

**Comment by LeandroStanger** [comment]
working
![captura de tela de 2018-12-19 17-21-56](https://user-images.githubusercontent.com/26097419/50242926-6f693400-03aa-11e9-8992-59d8270e92d1.png)
